[global.databases]
diesel_postgres_pool = { url = "postgres://postgres:1234@localhost:5432/foobardb"}

[global.oauth.github]
provider = "GitHub"
client_id = "712dd589696e92155cd2"
client_secret = "secret"
redirect_uri = "http://localhost:8000/api/auth/github"
